language: generic
matrix:
  include:
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: >-
        CC=gcc-4.9
        CXX=g++-4.9
        BUILD_TYPE=Debug
        COVERALLS=OFF
        TEST_TARGET=test

    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
      env: >-
        CC=clang-4.0
        CXX=clang++-4.0
        BUILD_TYPE=Debug
        COVERALLS=OFF
        TEST_TARGET=test

    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: >-
        CC=gcc-4.9
        CXX=g++-4.9
        BUILD_TYPE=Debug
        TEST_TARGET=coveralls
        COVERALLS=ON

    - os: osx
      env: >-
        CC=clang
        CXX=clang++
        BUILD_TYPE=Debug
        TEST_TARGET=test
        COVERALLS=OFF

# we may need to install libcurl, valgrind, and the custom version of libcurl
# that is built against gnutls.
script:
  - printenv
  - cmake --version
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCOVERALLS=${COVERALLS} ..
  - make
  - make ${TEST_TARGET}
